//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmountForm.ServRef_wcf_online {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServRef_wcf_online.IPPSI_ServiceWCF")]
    public interface IPPSI_ServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPPSI_ServiceWCF/AddAmount", ReplyAction="http://tempuri.org/IPPSI_ServiceWCF/AddAmountResponse")]
        void AddAmount(int amount, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPPSI_ServiceWCF/AddAmount", ReplyAction="http://tempuri.org/IPPSI_ServiceWCF/AddAmountResponse")]
        System.Threading.Tasks.Task AddAmountAsync(int amount, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPPSI_ServiceWCF/GetAvailableAmount", ReplyAction="http://tempuri.org/IPPSI_ServiceWCF/GetAvailableAmountResponse")]
        double GetAvailableAmount(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPPSI_ServiceWCF/GetAvailableAmount", ReplyAction="http://tempuri.org/IPPSI_ServiceWCF/GetAvailableAmountResponse")]
        System.Threading.Tasks.Task<double> GetAvailableAmountAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPPSI_ServiceWCFChannel : AmountForm.ServRef_wcf_online.IPPSI_ServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PPSI_ServiceWCFClient : System.ServiceModel.ClientBase<AmountForm.ServRef_wcf_online.IPPSI_ServiceWCF>, AmountForm.ServRef_wcf_online.IPPSI_ServiceWCF {
        
        public PPSI_ServiceWCFClient() {
        }
        
        public PPSI_ServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PPSI_ServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPSI_ServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPSI_ServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddAmount(int amount, string username) {
            base.Channel.AddAmount(amount, username);
        }
        
        public System.Threading.Tasks.Task AddAmountAsync(int amount, string username) {
            return base.Channel.AddAmountAsync(amount, username);
        }
        
        public double GetAvailableAmount(string username) {
            return base.Channel.GetAvailableAmount(username);
        }
        
        public System.Threading.Tasks.Task<double> GetAvailableAmountAsync(string username) {
            return base.Channel.GetAvailableAmountAsync(username);
        }
    }
}
